### ISSUE TITLE
Shouldn't this be part of the VC API test suite?

### ISSUE THREAD

**Issue by peacekeeper** [w3c/vc-bitstring-status-list-test-suite#4]
I thought since support for revocation is part of the VC API, it should also be tested as part of the VC API test suite, no?

E.g. see here: https://github.com/w3c-ccg/vc-api-test-suite/blob/main/packages/vc-http-api-test-server/config/DigitalBazaar.js#L11

**Comment by msporny** [comment]
We're trying to modularize the test suites into more manageable pieces:

https://lists.w3.org/Archives/Public/public-credentials/2022Apr/0126.html

Since it is not mandatory to implement revocation, and since status-list-2021 isn't the default agreed upon status mechanism, we thought we'd start it out as a separate module first. This allows organizations to demonstrate support for the status list mechanism AND support for status modification as an optional thing, instead of it being art of the core VC API test suite, which we expect to be deprecated in favor of the more modular testing architecture proposed above.

Thoughts?
